server:
  port: 9000
  servlet:
    context-path: /minprogram

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/minprogram?useUnicode=true&characterEncoding=UTF-8&useSSL=false&amp;zeroDateTimeBehavior=convertToNull
  username: root
  password: 123456

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.jiangdong.minprogram.entity

